#--- Base Config is a Config that applies to every environment like kind, digital ocean, aws and ...
apiVersion: v1
kind: Namespace
metadata:
  name: sales-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-pod
  namespace: sales-system
spec:
  selector:
    matchLabels:
      app: sales
  template:
    metadata:
      labels:
        app: sales
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      initContainers:
        - name: init-migrate
          image: sales-api-image
          command: ['./admin']
      containers:
# #_zipkin_1
        - name: zipkin
          image: openzipkin
          ports:
            - name: zipkin
              containerPort: 9411
        - name: sales-api
          image: sales-api-image
          ports:
            - name: sales-api
              containerPort: 3000
            - name: sales-api-debug
              containerPort: 4000

##
          readinessProbe:
            httpGet:
              path: /debug/liveness
              port: 4000
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /debug/readiness
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBERNETES_PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBERNETES_NAMESPACE_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBERNETES_NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

---
apiVersion: v1
kind: Service
metadata:
  name: sales-api
  namespace: sales-system
spec:
  type: ClusterIP
  selector:
    app: sales
  ports:
    - name: sales-api
      port: 3000
      targetPort: sales-api
    - name: sales-api-debug
      port: 4000
      targetPort: sales-api-debug
# #_zipkin_2
    - name: zipkin
      port: 9411
      targetPort: zipkin
