apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/sales-pod/
patches:
- path: ./kind-sales-patch.yaml

# find the name and replace them like variable
#- name: sales
#  newName: sales-api
#  newTag: 1.0.0
images:
- name: openzipkin
  newName: openzipkin/zipkin
  newTag: "2.23"
- name: sales-api-image
  newName: sales-api
  newTag: 1.0.0
